apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server-github
  labels:
    app: python-server-app
spec:
  selector:
    matchLabels:
        app: python-server-app
  replicas: 4
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-server-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node
                operator: In
                values:
                - ubuntu
      containers:
        - name: python-server-app
          image: gcr.io/schandu/pythonserver@sha256:0f177d35ab3ec3c9a3bdc5d33c7cbf9ee1d180af9ab44fd1285d77c41f6b0391
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
